<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
<channel>
<title><![CDATA[鸟语天空]]></title> 
<description><![CDATA[不怨天,不尤人,下学而上达,知我者其天乎!]]></description>
<link>http://www.devacg.com/</link>
<language>zh-cn</language>
<generator>www.emlog.net</generator>
<item>
	<title>AndroidStudio导出aar</title>
	<link>http://www.devacg.com/?post=1156</link>
	<description><![CDATA[步骤1 步骤2 <a href="http://www.devacg.com/?post=1156">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Sun, 10 Nov 2019 14:44:23 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=1156</guid>

</item>
<item>
	<title>自定义头像</title>
	<link>http://www.devacg.com/?post=752</link>
	<description><![CDATA[让玩家通过从相册选择照片或拍照来制作自己的头像 以下为demo AndroidManifest.xml  ?xml version=1.0 encoding=utf-8?   manifest xmlns:android=http://schemas.android.com/apk/res/android package=com.example.testcam android:versionCode=1 android:versionName... <a href="http://www.devacg.com/?post=752">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Mon, 29 Jan 2018 07:16:19 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=752</guid>

</item>
<item>
	<title>退出App</title>
	<link>http://www.devacg.com/?post=663</link>
	<description><![CDATA[//通过关进程退出App private void exitApp() { mActivity.runOnUiThread(new Runnable(){ @Override public void run() { //Android退出方式 android.os.Process.killProcess(android.os.Process.myPid()); //Java VM退出方式 System.exit(0); //官方推荐这种方式 //需要权限 uses-permission android:name=android.permission.... <a href="http://www.devacg.com/?post=663">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Sat, 16 Sep 2017 04:13:39 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=663</guid>

</item>
<item>
	<title>apktool.yml</title>
	<link>http://www.devacg.com/?post=661</link>
	<description><![CDATA[apktool.yml是反编译后生成的一个文件。 通过查看此文件可以知道apktool在生成apk时未对哪些文件或目录进行压缩 ... <a href="http://www.devacg.com/?post=661">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Fri, 15 Sep 2017 08:15:25 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=661</guid>

</item>
<item>
	<title>APK优化工具zipalign.exe</title>
	<link>http://www.devacg.com/?post=660</link>
	<description><![CDATA[使用zipalign.exe工具优化apk文件 优化原理: 通过zipalign工具优化apk文件对齐标准，使处理器可以快速准确的在内存地址中定位相关资源。 zipalign.exe所在位置 {Android SDK目录}/build-tools/xx.x.x/zipalign.exe 使用方式 在cmd中输入 zipalign.exe -f 4 优化前的.apk 优化后的.apk 如果希望输出详细信息就加个-v zipalign.exe -v -f 4 优化前的.apk 优化后的.apk <a href="http://www.devacg.com/?post=660">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Fri, 15 Sep 2017 02:58:33 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=660</guid>

</item>
<item>
	<title>离线安装gradle-x.x-all.zip</title>
	<link>http://www.devacg.com/?post=654</link>
	<description><![CDATA[一、手动下载，比如gradle-3.3-all.zip 二、放到{工程目录}\gradle\wrapper\gradle-3.3-all.zip 三、修改{工程目录}\gradle\wrapper\gradle-wrapper.properties #Tue Aug 22 19:47:27 CST 2017 distributionBase=GRADLE_USER_HOME distributionPath=wrapper/dists zipStoreBase=GRADLE_USER_HOME zipStorePath=... <a href="http://www.devacg.com/?post=654">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Tue, 22 Aug 2017 12:59:02 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=654</guid>

</item>
<item>
	<title>Unity接入Google游戏服务</title>
	<link>http://www.devacg.com/?post=651</link>
	<description><![CDATA[以下代码接入了Google的：广告、排行榜、分享、评论功能。 build.gradle配置 // GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN buildscript { repositories { jcenter() } dependencies { classpath 'com.android.tools.build:gradle:2.3.0' } dependencies { c... <a href="http://www.devacg.com/?post=651">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Thu, 17 Aug 2017 12:13:35 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=651</guid>

</item>
<item>
	<title>打开App所在Google商店的下载(评论)页面</title>
	<link>http://www.devacg.com/?post=650</link>
	<description><![CDATA[//打开App所在Google商店的下载页面(评论url) public void openCommentUrl() { Uri uri = Uri.parse(market://details?id= + this.getPackageName()); Intent goToMarket = new Intent(Intent.ACTION_VIEW, uri); goToMarket.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY | Intent.FLAG_ACTIV... <a href="http://www.devacg.com/?post=650">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Thu, 17 Aug 2017 12:08:22 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=650</guid>

</item>
<item>
	<title>Android存储目录</title>
	<link>http://www.devacg.com/?post=595</link>
	<description><![CDATA[getCacheDir() /data/user/0/{包名}/cache getExternalCacheDir() /storage/emulated/0/Android/data/{包名}/cache ... <a href="http://www.devacg.com/?post=595">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Thu, 22 Jun 2017 02:46:34 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=595</guid>

</item>
<item>
	<title>gradle-wrapper.properties</title>
	<link>http://www.devacg.com/?post=594</link>
	<description><![CDATA[文件位置 
项目路径\gradle\wrapper下有两个文件gradle-wrapper.jar、gradle-wrapper.properties 文件内容 #distributionBase和distributionPath组合在一起，是解压gradle-3.1-bin.zip之后的文件的存放位置
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
#zipStoreBase和zipStorePath组合在一起，是下载的gradle-3.1-bin.zip所存放的位置
zipStoreBase=GRADLE_U... <a href="http://www.devacg.com/?post=594">阅读全文&gt;&gt;</a>]]></description>
	<pubDate>Wed, 21 Jun 2017 05:54:09 +0000</pubDate>
	<author>追风剑情</author>
	<guid>http://www.devacg.com/?post=594</guid>

</item></channel>
</rss>